name: Scraping Manual La Vanguardia

on:
  workflow_dispatch: # Botón manual en la interfaz de GitHub

jobs:
  run_scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar librerías de Python
        run: |
          # Necesitamos requests para descargar la web, beautifulsoup4 para leerla y pandas para el CSV
          pip install requests beautifulsoup4 pandas

      - name: Ejecutar Scraping de La Vanguardia
        run: |
          python priviet.py
          
      - name: Guardar CSV generado en el repositorio
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Añade el nuevo archivo creado 'titulares_lavanguardia.csv'
          git add titulares_lavanguardia.csv
          
          if git diff --quiet && git diff --staged --quiet; then
            echo "No hay cambios nuevos en los titulares."
          else
            git commit -m "Prueba Scraping: Titulares actualizados [skip ci]"
            git push origin main
          fi
